name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: "Info"
      run: |
        echo ${{ github.repo }}
        echo ${{ github.ref }}

    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependency cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
      
    - name: npm install
      run: npm install
      
    - name: npm run cleancoverage
      run: npm run cleancoverage
